export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as NewTicketPage } from './NewTicketPage'
export { default as TicketsPage } from './TicketsPage'
export { default as TicketPage } from './TicketPage'
